# Generated by Django 5.0.3 on 2024-03-23 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_comment_watchlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
