# Generated by Django 5.0.3 on 2024-03-23 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='starting_bid',
            field=models.FloatField(),
        ),
    ]
