# Generated by Django 5.0.3 on 2024-03-24 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_alter_bid_bid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listings',
            name='category',
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('item', models.ManyToManyField(blank=True, related_name='categories', to='auctions.listings')),
            ],
        ),
    ]
