# Generated by Django 5.0.3 on 2024-03-25 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_alter_category_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='image',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
