# Generated by Django 5.0.3 on 2024-03-29 05:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0018_listings_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='starting_bid',
            field=models.DecimalField(decimal_places=2, max_digits=20, validators=[django.core.validators.MinValueValidator(0.1)]),
        ),
    ]
