# Generated by Django 5.0.3 on 2024-04-06 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_listings_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
